### ISSUE TITLE
semantics of the graph menu

### ISSUE THREAD

**Issue by klaernie** [chteuchteu/Munin-for-Android#14]
In my mind, the graph menu should only contain servers, and not suddenly switch to the list of plugins within the currently selected server.

I view the menu on the left as a global menu, but as soon as one displays a graph it switches to the "useless" list of plugins, which forces me to go back a step, select another server from the drop down at the top and scroll back to the plugin I want to view.

In my understanding as soon as a graph is displayed the menu should only reflect the server list, with the current one highlighted, and choosing a server from the list should go to the same plugin I am currently viewing, just on this selected server.

**Comment by quentin-st** [comment]
I see your point here. Indeed, I also thought of deleting this plugins list since if can be quite useless and take some space in the drawer. (one has to scroll to the bottom of the list to see the Grids menu item for example).

Actually, there is already a "switch server" feature (available in the overflow menu, by cliking on the three dots icon). Plus, when switching from one plugin to another, the servers list would be different, so this wouldn't be really consistent and may confuse user... Then, we would have to update this servers list every time the user switches to a different graph (by swiping left or right), which would be bad for performances...

I thought we agree that this plugins list should be deleted.

I'm thinking about creating a list-detail layout for this. This wouldn't be easy since the layout is quite complicated, but this would allow quicker switching between list and graph. Also, this would allow tablets users to have the plugins list on the left, and the graph on the right. Just have to figure it out!

**Comment by klaernie** [comment]
I didn't mean limit the server-list to servers, that carry the same plugin. The server list should always contain the full list.

The "same plugin" idea is more like a bit of candy: if the new server has the same plugin as is currently show on the old server, display it, else display the first plugin found.

**Comment by quentin-st** [comment]
Yes, that would be a better idea!
