### ISSUE TITLE
SNI support on Android < Lollipop

### ISSUE THREAD

**Issue by quentin-st** [chteuchteu/Munin-for-Android#22]
Currently, SNI (Server Name Indication) only works on devices running Android Lollipop, for no apparent reason. It would be great to make it work for lower Android versions as well.

It may have something to do with `CustomSSLFactory` class (or not).

**Comment by aalmenar** [comment]
This may looks like: "Fortunately, HttpsURLConnection supports SNI since Android 2.3. Unfortunately, Apache HTTP Client does not, which is one of the many reasons we discourage its use. One workaround if you need to support Android 2.2 (and older) or Apache HTTP Client is to set up an alternative virtual host on a unique port so that it's unambiguous which server certificate to return."

This is explained: https://developer.android.com/training/articles/security-ssl.html#CommonHostnameProbs

**Comment by quentin-st** [comment]
I didn't knew about the unique port trick, thanks!

I think I'll write a documentation about this on the repo's readme file so users will know how to configure their server

**Comment by quentin-st** [comment]
Good news! I removed Apache HTTP Client to introduce Http(s)URLConnection in 6bbe3f9, fixing this SNI issue. This change will be shipped in the upcoming update!
