### ISSUE TITLE
Dynazoom graphs zoom in time

### ISSUE THREAD

**Issue by Phoenix1o1** [chteuchteu/Munin-for-Android#33]
So, after figuring out how to make dynazoom working properly, I noticed that when zooming in the timestamps seem to be somehow wrong.I will upload a video to show you where.

**Comment by Phoenix1o1** [comment]
http://sendvid.com/uux3eqzq

**Comment by quentin-st** [comment]
Hi,
Thank you for the video! There is indeed some problems with the datetimes...

The issue seems to come from [Activity_GraphView:937:940](https://github.com/chteuchteu/Munin-for-Android/blob/master/muninforAndroid/src/main/java/com/chteuchteu/munin/ui/Activity_GraphView.java#L937-L940):

```
long new_dynazoom_from = dynazoom_from + (dynazoom_to-dynazoom_from) * fromIndex / DynazoomHelper.RANGEBAR_TICKS_COUNT;
long new_dynazoom_to = dynazoom_from + (dynazoom_to-dynazoom_from) * toIndex / DynazoomHelper.RANGEBAR_TICKS_COUNT;

dynazoom_updateFromTo(new_dynazoom_from, new_dynazoom_to);
```

`new_dynazoom_from` & `new_dynazoom_to` are timestamps computed from the rangeBar indexes & the current `dynazoom_from` & `dynazoom_to` values. `dynazoom_updateFromTo` updates the TextViews.

I don't have much time to investigate for now - but if you find where it comes from, don't hesitate to comment here or open a pull-request!

Thank you for your help on this issue!

**Comment by quentin-st** [comment]
Sorry for the long time it took, but I finally found the source of the issue.
If you look at the [changelog](https://github.com/chteuchteu/Munin-for-Android/commit/00874955eee198eaef23bbd180cfec6a6a2160bc), you'll see two issues:
- `new_dynazoom_to` should be computed using `rightThumbIndex+1`, not just `rightThumbIndex`. This was the source of the issue at 0:38 on your video
- we have to use temp variables when updating `dynazoom_from` & `dynazoom_to` on graph click. This was the source of the issue at 0:45 on your video

Thanks for your patience, I'll publish a new version of the app right away.
