### ISSUE TITLE
[feature request] add category in the plugin selection for grid

### ISSUE THREAD

**Issue by quazardous** [chteuchteu/Munin-for-Android#34]
HI,

great work !

just if you could add the category in the plugins selection widget when adding to grid.

Some times plugins have identical names in different category.

best regards
david

**Comment by quentin-st** [comment]
Hi, David, and thank you!

I began refactoring the plugins dialog (in the [multilevel-searchable-alertdialog](https://github.com/chteuchteu/Munin-for-Android/tree/multilevel-searchable-alertdialog) branch), but I gave up due to mediocre performances...

Anyway, this is indeed a good idea, I'll add it soon. Please switch to the beta channel ([instructions here](https://github.com/chteuchteu/Munin-for-Android#beta)) - I'll release a new version on it as soon as possible.

**Comment by quazardous** [comment]
thx
ps : t fr ? avec un pseudo pareil...

**Comment by quentin-st** [comment]
Le pseudo ne fait pas le moine ;)

**Comment by quentin-st** [comment]
Let's continue this in English so other people may follow.

We're now displaying the category name alongside with the plugin name, see [commit](https://github.com/chteuchteu/Munin-for-Android/commit/b78d16592df90a605aad72ce5ecd526646cdd14c) for details.
I've also just release v3.6.5-beta8, it should be available soon on your device:

![2016-01-12 18 44 53](https://cloud.githubusercontent.com/assets/1551971/12273551/ca719fa4-b966-11e5-809a-4a32b4c7adfe.png)

**Comment by quazardous** [comment]
nice and so quick !
